version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8083:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    notificationservice1:
        image: notificationservice
        environment:
            - APPID=1111
    notificationservice2:
        image: notificationservice
        environment:
            - APPID=2222
    notificationservice3:
        image: notificationservice
        environment:
            - APPID=3333
    notificationservice4:
        image: notificationservice
        environment:
            - APPID=4444